export enum STAMPS {
  THUMBS_UP = '👍',
  THUMBS_UP_LIGHT = '👍🏻',
  THUMBS_UP_MEDIUM_LIGHT = '👍🏼',
  THUMBS_UP_MEDIUM= '👍🏽',
  THUMBS_UP_MEDIUM_DARK = '👍🏾',
  THUMBS_UP_DARK = '👍🏿',
}

export const THUMBS_UPS = [
  STAMPS.THUMBS_UP,
  STAMPS.THUMBS_UP_LIGHT,
  STAMPS.THUMBS_UP_MEDIUM_LIGHT,
  STAMPS.THUMBS_UP_MEDIUM,
  STAMPS.THUMBS_UP_MEDIUM_DARK,
  STAMPS.THUMBS_UP_DARK,
];